# check info on https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       uploaded_image:
           uri_prefix: /images
           upload_destination: '%kernel.project_dir%/public/images/uploaded'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true